#!/usr/bin/bash
rm -f public/html
ln -s /media/ikm/WD35/text/kristen/html public/html
ln -sf /media/ikm/WD35/text/kristen/data.json src/data.json
#ln -s /media/ikm/WD35/text/cssa_reader/html public/html
#ln -sf /media/ikm/WD35/text/cssa_reader/data.json src/data.json
